
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in"><a name="_GoBack"></a>
    <font color="#e1efff">  a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">9</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff">b</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">6</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff">a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#e1efff">a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">+</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">4</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff">b</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#e1efff">b</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">+</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">2</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff">a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#e1efff">a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">+</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">10</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff">b</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#e1efff">b</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">-</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">25</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff">a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#e1efff">a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">-</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">20</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff">b</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#e1efff">b</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">+</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">5</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff">a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#e1efff">a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">+</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">4</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff">b</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#e1efff">b</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">+</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">2</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff">a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">=</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#e1efff">a</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff9d00">+</font></font></font><font color="#ffffff">&nbsp;</font></font></font><font color="#ff628c">10</font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">-</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff628c"><span lang="en-US">10</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;<span lang="en-US">document</span></font></font></font><font color="#e1efff"><span lang="en-US">.</span></font></font></font><font color="#ffc600"><span lang="en-US">getElementById</span></font></font></font><font color="#e1efff"><span lang="en-US">(</span></font></font></font><font color="#92fc79"><span lang="en-US">"</span></font></font></font><font color="#a5ff90"><span lang="en-US">3</span></font></font></font><font color="#92fc79"><span lang="en-US">"</span></font></font></font><font color="#e1efff"><span lang="en-US">).</span></font></font></font><font color="#9effff"><span lang="en-US">innerHTML</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#3ad900"><span lang="en-US">`</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#3ad900">&nbsp;&nbsp;</font><font color="#3ad900">a&nbsp;=&nbsp;</font></font></font><font color="#ffee80">${</font></font></font><font color="#e1efff">a</font></font></font><font color="#ffee80">}</font></font></font><font color="#ff628c">\n\n</font></font></font><font color="#3ad900">&nbsp;&nbsp;b&nbsp;=&nbsp;</font></font></font><font color="#ffee80">${</font></font></font><font color="#e1efff">b</font></font></font><font color="#ffee80">}</font></font></font><font color="#3ad900">`</font></font></font><font color="#e1efff">;</font></font></font><font color="#ffffff">&nbsp;</font></font></font></p>
