    <font color="#ffffff"></font><font color="#e1efff">a</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">=</font><font color="#ffffff">&nbsp;</font><font color="#ff628c">10</font></p>
    <p  background: #193549>
    <font color="#ffffff"></font><font color="#e1efff">b</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">=</font><font color="#ffffff">&nbsp;</font><font color="#ff628c">20</font></p>
    <p  background: #193549>
    <font color="#ffffff"></font><font color="#e1efff">c</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">=</font><font color="#ffffff">&nbsp;</font><font color="#ff628c">5</font></p>
    <p  background: #193549>
    <font color="#ffffff"></font><font color="#e1efff">a</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">=</font><font color="#ffffff">&nbsp;</font><font color="#e1efff">a</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">+</font><font color="#ffffff">&nbsp;</font><font color="#ff628c">3</font></p>
    <p  background: #193549>
    <font color="#ffffff"></font><font color="#e1efff">b</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">=</font><font color="#ffffff">&nbsp;</font><font color="#e1efff">b</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">+</font><font color="#ffffff">&nbsp;</font><font color="#ff628c">4</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">-</font><font color="#ffffff">&nbsp;</font><font color="#e1efff">a</font></p>
    <p  background: #193549>
    <font color="#ffffff"></font><font color="#e1efff">c</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">=</font><font color="#ffffff">&nbsp;</font><font color="#e1efff">a</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">+</font><font color="#ffffff">&nbsp;</font><font color="#e1efff">b</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">+</font><font color="#ffffff">&nbsp;</font><font color="#e1efff">c</font></p>
    <p  background: #193549>
    <font color="#ffffff"></font><font color="#e1efff">a</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">=</font><font color="#ffffff">&nbsp;</font><font color="#e1efff">a</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">+</font><font color="#ffffff">&nbsp;</font><font color="#e1efff">c</font></p>
    <p  background: #193549>
    <font color="#ffffff"></font><font color="#e1efff">b</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">=</font><font color="#ffffff">&nbsp;</font><font color="#ff628c">4</font></p>
    <p  background: #193549>
    <font color="#ffffff"></font><font color="#e1efff">c</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">=</font><font color="#ffffff">&nbsp;</font><font color="#e1efff">c</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">+</font><font color="#ffffff">&nbsp;</font><font color="#ff628c">3</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">-</font><font color="#ffffff">&nbsp;</font><font color="#e1efff">b</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">+</font><font color="#ffffff">&nbsp;</font><font color="#ff628c">2</font></p>
    <p  background: #193549>
    <p  background: #193549>
    <font color="#ffffff">document</font><font color="#e1efff">.</font><font color="#ffc600">getElementById</font><font color="#e1efff">(</font><font color="#92fc79">"</font><font color="#a5ff90">1</font><font color="#92fc79">"</font><font color="#e1efff">).</font><font color="#9effff">innerHTML</font><font color="#ffffff">&nbsp;</font><font color="#ff9d00">=</font><font color="#ffffff">&nbsp;</font><font color="#3ad900">`a&nbsp;=&nbsp;</font><font color="#ffee80">${</font><font color="#e1efff">a</font><font color="#ffee80">}</font><font color="#3ad900">&nbsp;</font><font color="#ff628c">\n</font><font color="#3ad900">b&nbsp;=&nbsp;</font><font color="#ffee80">${</font><font color="#e1efff">b</font><font color="#ffee80">}</font><font color="#3ad900">&nbsp;</font><font color="#ff628c">\n</font><font color="#3ad900">c&nbsp;=&nbsp;</font><font color="#ffee80">${</font><font color="#e1efff">c</font><font color="#ffee80">}</font><font color="#3ad900">`</font><font color="#e1efff">;</font></p>

