    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp; </font><font color="#e1efff"><span lang="en-US">a</span></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff628c"><span lang="en-US">5</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff628c"><span lang="en-US">18</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">c</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff628c"><span lang="en-US">15</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">d</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff628c"><span lang="en-US">25</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">a</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">a</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">+</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff628c"><span lang="en-US">10</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">+</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff628c"><span lang="en-US">5</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">-</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">c</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">c</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">c</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">+</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff628c"><span lang="en-US">4</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">+</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">b</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">d</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">d</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">+</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">+</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">a</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">a</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">a</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">+</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff628c"><span lang="en-US">1</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">+</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">c</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">c</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">+</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">c</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in"><a name="_GoBack"></a>
    <font color="#ffffff">&nbsp;&nbsp;</font><font color="#e1efff"><span lang="en-US">d</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">+</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#e1efff"><span lang="en-US">b</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#ffffff">&nbsp;&nbsp;<span lang="en-US">document</span></font></font></font><font color="#e1efff"><span lang="en-US">.</span></font></font></font><font color="#ffc600"><span lang="en-US">getElementById</span></font></font></font><font color="#e1efff"><span lang="en-US">(</span></font></font></font><font color="#92fc79"><span lang="en-US">"</span></font></font></font><font color="#a5ff90"><span lang="en-US">2</span></font></font></font><font color="#92fc79"><span lang="en-US">"</span></font></font></font><font color="#e1efff"><span lang="en-US">).</span></font></font></font><font color="#9effff"><span lang="en-US">innerHTML</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#ff9d00"><span lang="en-US">=</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font><font color="#3ad900"><span lang="en-US">`</span></font></font></font></p>
    <p style="margin-bottom: 0in; background: #193549; line-height: 0.2in">
    <font color="#3ad900">&nbsp;&nbsp;<span lang="en-US">a&nbsp;=&nbsp;</span></font></font></font><font color="#ffee80"><span lang="en-US">${</span></font></font></font><font color="#e1efff"><span lang="en-US">a</span></font></font></font><font color="#ffee80"><span lang="en-US">}</span></font></font></font><font color="#ff628c"><span lang="en-US">\n\n</span></font></font></font><font color="#3ad900"><span lang="en-US">&nbsp;&nbsp;b&nbsp;=&nbsp;</span></font></font></font><font color="#ffee80"><span lang="en-US">${</span></font></font></font><font color="#e1efff"><span lang="en-US">b</span></font></font></font><font color="#ffee80"><span lang="en-US">}</span></font></font></font><font color="#ff628c"><span lang="en-US">\n\n</span></font></font></font><font color="#3ad900"><span lang="en-US">&nbsp;&nbsp;c&nbsp;=&nbsp;</span></font></font></font><font color="#ffee80"><span lang="en-US">${</span></font></font></font><font color="#e1efff"><span lang="en-US">c</span></font></font></font><font color="#ffee80"><span lang="en-US">}</span></font></font></font><font color="#ff628c"><span lang="en-US">\n\n</span></font></font></font><font color="#3ad900"><span lang="en-US">&nbsp;&nbsp;d&nbsp;=&nbsp;</span></font></font></font><font color="#ffee80"><span lang="en-US">${</span></font></font></font><font color="#e1efff"><span lang="en-US">d</span></font></font></font><font color="#ffee80"><span lang="en-US">}</span></font></font></font><font color="#3ad900"><span lang="en-US">`</span></font></font></font><font color="#e1efff"><span lang="en-US">;</span></font></font></font><font color="#ffffff"><span lang="en-US">&nbsp;</span></font></font></font></p>
